tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "python@3.10"
brew "ansible"
brew "gh"
brew "git"
brew "mas"
brew "neovim"
brew "pyenv"
brew "ripgrep"
brew "node@16"
brew "tmux"
brew "zsh-syntax-highlighting"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "qmk/qmk/qmk"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "karabiner-elements"
cask "qmk-toolbox"
cask 'google-chrome'
cask 'spotify'
cask 'iterm2'
cask 'iina'
cask 'obsidian'
cask 'raycast'
cask 'bitwarden'
cask 'calibre'
cask 'keka'
cask 'transmission'
cask 'aldente'
cask 'firefox'
